r"""Turn a git tag into the two version files the build needs (spec 11.1).

    uv run python -m scripts.stamp_version v1.2.0 \
        --module farmsync_solver/_version.py \
        --version-file build/file_version_info.txt

The tag is the single source of version truth. `farmsync_solver/_version.py` is
committed holding the `0.0.0-dev` placeholder and is overwritten here at build
time, so "tagged 1.0.1, file still says 1.0.0" cannot happen.

It prints `version=`, `numeric=` and `prerelease=` lines for the release workflow
to read. `numeric=` is the three-number part alone, which is all the installer's
`VersionInfoVersion` accepts.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

APP_NAME = "FarmsyncSolver"

# v1.2.0 or v1.2.0-rc1. Three numbers, no more: a fourth would not survive the
# round trip through the Windows file properties, which hold exactly four and
# reserve the last one.
TAG = re.compile(r"^(?:refs/tags/)?v(?P<version>(?P<numbers>\d+\.\d+\.\d+)(?:-[0-9A-Za-z.-]+)?)$")


def version_from_tag(tag: str) -> str:
    """`v1.2.0-rc1` -> `1.2.0-rc1`. Anything else is a build failure."""
    match = TAG.match(tag.strip())
    if match is None:
        raise ValueError(f"tag is not a version tag: {tag!r}")
    return match.group("version")


def is_prerelease(version: str) -> bool:
    """A dash means a pre-release, which `releases/latest` skips."""
    return "-" in version


def numeric_version(version: str) -> str:
    """`1.2.0-rc1` -> `1.2.0`. Inno Setup's VersionInfoVersion takes numbers only."""
    return version.split("-", 1)[0]


def file_version_tuple(version: str) -> tuple[int, int, int, int]:
    """The four numbers Windows file properties hold. The pre-release part is lost."""
    numbers = numeric_version(version).split(".")
    major, minor, patch = (int(number) for number in numbers)
    return (major, minor, patch, 0)


def version_module_source(version: str) -> str:
    """The whole of `farmsync_solver/_version.py`, version swapped in."""
    return (
        '"""Version strings. Regenerated at build time from the git tag (see spec 11.1)."""\n'
        "from __future__ import annotations\n"
        "\n"
        f'APP_NAME = "{APP_NAME}"\n'
        f'VERSION = "{version}"\n'
    )


def version_file_source(version: str) -> str:
    """PyInstaller's `--version-file`: the same number, on the `.exe` properties."""
    numbers = file_version_tuple(version)
    return f"""# Generated by scripts/stamp_version.py. Do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={numbers},
    prodvers={numbers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', '{APP_NAME}'),
            StringStruct('FileDescription', '{APP_NAME}'),
            StringStruct('FileVersion', '{version}'),
            StringStruct('InternalName', '{APP_NAME}'),
            StringStruct('OriginalFilename', '{APP_NAME}.exe'),
            StringStruct('ProductName', '{APP_NAME}'),
            StringStruct('ProductVersion', '{version}'),
          ],
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("tag", help="the git tag, for example v1.2.0")
    parser.add_argument("--module", required=True, type=Path, help="where _version.py goes")
    parser.add_argument(
        "--version-file", required=True, type=Path, help="where PyInstaller's version file goes"
    )
    arguments = parser.parse_args(argv)

    version = version_from_tag(arguments.tag)

    for path, source in (
        (arguments.module, version_module_source(version)),
        (arguments.version_file, version_file_source(version)),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")

    print(f"version={version}")
    print(f"numeric={numeric_version(version)}")
    print(f"prerelease={'true' if is_prerelease(version) else 'false'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
